name: Build Linux Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Make build script executable
        run: chmod +x GenerateExecutable/build_linux.sh
      - name: Build Linux Executable
        run: ./GenerateExecutable/build_linux.sh || true
      - name: Upload Linux Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: GenerateExecutable/linux/ExcelTableTools