name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: true
        type: boolean
        default: false

jobs:
  build-all:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: ExcelTableTools
            asset_name: ExcelTableTools-linux
          - os: windows-latest
            platform: windows
            artifact_name: ExcelTableTools.exe
            asset_name: ExcelTableTools-windows
          - os: macos-latest
            platform: macos
            artifact_name: ExcelTableTools
            asset_name: ExcelTableTools-macos
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Install Linux/Windows dependencies
      if: matrix.platform != 'macos'
      run: |
        pip install -r requirements.txt
    
    - name: Install macOS dependencies
      if: matrix.platform == 'macos'
      run: |
        pip install -r requirements-macos.txt
    
    - name: Build Linux
      if: matrix.platform == 'linux'
      run: |
        chmod +x GenerateExecutable/build_linux.sh
        ./GenerateExecutable/build_linux.sh
    
    - name: Build Windows
      if: matrix.platform == 'windows'
      run: |
        GenerateExecutable\build_windows.bat
    
    - name: Build macOS
      if: matrix.platform == 'macos'
      run: |
        chmod +x GenerateExecutable/build_macos.sh
        ./GenerateExecutable/build_macos.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: GenerateExecutable/${{ matrix.platform }}/${{ matrix.artifact_name }}
        if-no-files-found: error

  create-release:
    needs: build-all
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create release
        response=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{
            "tag_name":"${{ github.event.inputs.version }}",
            "target_commitish":"${{ github.sha }}",
            "name":"Release ${{ github.event.inputs.version }}",
            "body":"Release ${{ github.event.inputs.version }}",
            "draft":false,
            "prerelease":${{ github.event.inputs.prerelease }}
          }')
        
        # Extract release ID
        release_id=$(echo $response | jq -r .id)
        
        # Upload Linux binary
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=ExcelTableTools-linux" \
          --data-binary "@artifacts/ExcelTableTools-linux/ExcelTableTools"
        
        # Upload Windows binary
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=ExcelTableTools-windows.exe" \
          --data-binary "@artifacts/ExcelTableTools-windows/ExcelTableTools.exe"
        
        # Upload macOS binary
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=ExcelTableTools-macos" \
          --data-binary "@artifacts/ExcelTableTools-macos/ExcelTableTools"