name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: true
        type: boolean
        default: false

jobs:
  build-all:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: ExcelTableTools
            asset_name: ExcelTableTools-linux
          - os: windows-latest
            platform: windows
            artifact_name: ExcelTableTools.exe
            asset_name: ExcelTableTools-windows
          - os: macos-latest
            platform: macos
            artifact_name: ExcelTableTools
            asset_name: ExcelTableTools-macos
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Install Linux/Windows dependencies
      if: matrix.platform != 'macos'
      run: |
        pip install -r requirements.txt
    
    - name: Install macOS dependencies
      if: matrix.platform == 'macos'
      run: |
        pip install -r requirements-macos.txt
    
    - name: Build Linux
      if: matrix.platform == 'linux'
      run: |
        chmod +x GenerateExecutable/build_linux.sh
        ./GenerateExecutable/build_linux.sh
    
    - name: Build Windows
      if: matrix.platform == 'windows'
      shell: cmd
      run: |
        GenerateExecutable\build_windows.bat
    
    - name: Build macOS
      if: matrix.platform == 'macos'
      run: |
        chmod +x GenerateExecutable/build_macos.sh
        ./GenerateExecutable/build_macos.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: |
          GenerateExecutable/${{ matrix.platform }}/${{ matrix.artifact_name }}
          GenerateExecutable/${{ matrix.platform }}/${{ matrix.artifact_name }}.app/**
        if-no-files-found: error

  create-release:
    needs: build-all
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Debug artifact structure
      run: |
        echo "Artifact structure:"
        find artifacts -type f -ls
        echo ""
        echo "Directory contents:"
        ls -la artifacts/
        for dir in artifacts/*/; do
          echo "Contents of $dir:"
          ls -la "$dir"
        done
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create release
        response=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{
            "tag_name":"${{ github.event.inputs.version }}",
            "target_commitish":"${{ github.sha }}",
            "name":"Release ${{ github.event.inputs.version }}",
            "body":"Release ${{ github.event.inputs.version }}",
            "draft":false,
            "prerelease":${{ github.event.inputs.prerelease }}
          }')
        
        echo "Release creation response: $response"
        
        # Extract release ID
        release_id=$(echo $response | jq -r .id)
        echo "Release ID: $release_id"
        
        if [ "$release_id" = "null" ] || [ -z "$release_id" ]; then
          echo "Failed to create release or extract release ID"
          echo "Response: $response"
          exit 1
        fi
        
        # Upload Linux binary
        if [ -f "artifacts/ExcelTableTools-linux/ExcelTableTools" ]; then
          echo "Uploading Linux binary..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=ExcelTableTools-linux" \
            --data-binary "@artifacts/ExcelTableTools-linux/ExcelTableTools"
        else
          echo "Linux binary not found at artifacts/ExcelTableTools-linux/ExcelTableTools"
        fi
        
        # Upload Windows binary
        if [ -f "artifacts/ExcelTableTools-windows/ExcelTableTools.exe" ]; then
          echo "Uploading Windows binary..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=ExcelTableTools-windows.exe" \
            --data-binary "@artifacts/ExcelTableTools-windows/ExcelTableTools.exe"
        else
          echo "Windows binary not found at artifacts/ExcelTableTools-windows/ExcelTableTools.exe"
        fi
        
        # Upload macOS binary (handle both standalone and app bundle)
        if [ -f "artifacts/ExcelTableTools-macos/ExcelTableTools" ]; then
          echo "Uploading macOS standalone binary..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=ExcelTableTools-macos" \
            --data-binary "@artifacts/ExcelTableTools-macos/ExcelTableTools"
        elif [ -d "artifacts/ExcelTableTools-macos/ExcelTableTools.app" ]; then
          echo "Creating zip of macOS app bundle..."
          # Create a zip of the app bundle
          cd artifacts/ExcelTableTools-macos
          zip -r ExcelTableTools-macos.zip ExcelTableTools.app
          cd ../..
          echo "Uploading macOS app bundle..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/zip" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=ExcelTableTools-macos.zip" \
            --data-binary "@artifacts/ExcelTableTools-macos/ExcelTableTools-macos.zip"
        else
          echo "macOS binary not found at expected locations"
        fi
        
        echo "Release creation and asset upload completed"